# -*- coding: utf-8 -*-
"""Chapter1-EXERCISE1,2,3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YeiPckUBJDGrY0jRAzW0O4wy7fLW3uij
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **EXERCISE 1**"""

Print('Hello world!')

"""MODIFIED CODE"""

print('Hello world!')

"""Explanation 1: the error is in Print. The letter p should be small letter not a capital letter P



"""

print'Hello world!')

"""MODIFIED CODE"""

print('Hello world!')

"""Explanation 2: *the* parenthesis should be 2 not one like this: print('any name')"""

print('Hello world!)

"""MODIFIED CODE"""

print('Hello world!')

"""Explanation 3: The error is in print('Hello world!). It should be like this: print('Hello world!') the quotation should be 2 single quotation both left and right not only 1"""

print('Hello world!'')

"""MODIFIED CODE"""

print('Hello world!')

"""# **EXERCISE** **2**

Explanation 4: The error is in ('Hello world!'') the quotation should be single not double. It should be like this print('Hello world!').
"""

x = 43
x = x + 1
print(x)

"""The output is 44, because we Initialze the x as 43 to solve for the formula of x= 43+1 that will print the output of 44

#***EXERCISE 3***
"""

x = 43
x = X + 1
print(x)

"""MODIFIED CODE"""

x = 43
x = x + 1
print(x)

"""The error is in big letter X which is the variable that we didnt initialize, because the variable that we initialize is small letter x.

# **CHALLENGES**

**CHALLENGE 1**
Write a program which repeatedly reads numbers until the user enters "done". Once "done" is entered, print out the total, count, and average of the numbers. If the user enters anything other than a number, detect their mistake using try and except and print an error message and skip to the next number.
"""

